import { AdminUser, AdminDecision, AdminAnalytics, AdminSettings } from './admin-types';

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'user-001',
    email: 'john.doe@example.com',
    name: 'John Doe',
    role: 'user',
    createdAt: '2024-01-15',
    lastLogin: '2024-05-12',
    isActive: true,
    decisionsCount: 24,
  },
  {
    id: 'user-002',
    email: 'jane.smith@example.com',
    name: 'Jane Smith',
    role: 'user',
    createdAt: '2024-02-10',
    lastLogin: '2024-05-13',
    isActive: true,
    decisionsCount: 18,
  },
  {
    id: 'user-003',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'admin',
    createdAt: '2024-01-01',
    lastLogin: '2024-05-14',
    isActive: true,
    decisionsCount: 5,
  },
  {
    id: 'user-004',
    email: 'bob.wilson@example.com',
    name: 'Bob Wilson',
    role: 'user',
    createdAt: '2024-03-05',
    lastLogin: '2024-05-10',
    isActive: true,
    decisionsCount: 12,
  },
  {
    id: 'user-005',
    email: 'alice.johnson@example.com',
    name: 'Alice Johnson',
    role: 'user',
    createdAt: '2024-03-20',
    lastLogin: '2024-04-28',
    isActive: false,
    decisionsCount: 8,
  },
  {
    id: 'user-006',
    email: 'charlie.brown@example.com',
    name: 'Charlie Brown',
    role: 'user',
    createdAt: '2024-04-01',
    lastLogin: '2024-05-13',
    isActive: true,
    decisionsCount: 15,
  },
];

export const mockAdminDecisions: AdminDecision[] = [
  {
    id: 'decision-001',
    userId: 'user-001',
    userName: 'John Doe',
    title: 'Choose Programming Language for New Project',
    status: 'completed',
    createdAt: '2024-05-10',
    updatedAt: '2024-05-12',
    alternativeCount: 4,
    criteriaCount: 5,
    score: 92,
  },
  {
    id: 'decision-002',
    userId: 'user-002',
    userName: 'Jane Smith',
    title: 'Select Cloud Provider for Deployment',
    status: 'completed',
    createdAt: '2024-05-08',
    updatedAt: '2024-05-11',
    alternativeCount: 3,
    criteriaCount: 6,
    score: 88,
  },
  {
    id: 'decision-003',
    userId: 'user-001',
    userName: 'John Doe',
    title: 'Laptop Purchase Decision',
    status: 'completed',
    createdAt: '2024-05-05',
    updatedAt: '2024-05-09',
    alternativeCount: 5,
    criteriaCount: 7,
    score: 85,
  },
  {
    id: 'decision-004',
    userId: 'user-004',
    userName: 'Bob Wilson',
    title: 'Team Tool Selection',
    status: 'pending',
    createdAt: '2024-05-13',
    updatedAt: '2024-05-13',
    alternativeCount: 3,
    criteriaCount: 4,
    score: 0,
  },
  {
    id: 'decision-005',
    userId: 'user-002',
    userName: 'Jane Smith',
    title: 'Framework Decision - React vs Vue',
    status: 'completed',
    createdAt: '2024-04-20',
    updatedAt: '2024-05-02',
    alternativeCount: 2,
    criteriaCount: 8,
    score: 95,
  },
  {
    id: 'decision-006',
    userId: 'user-006',
    userName: 'Charlie Brown',
    title: 'Office Location Selection',
    status: 'archived',
    createdAt: '2024-03-15',
    updatedAt: '2024-04-10',
    alternativeCount: 4,
    criteriaCount: 6,
    score: 78,
  },
];

export const mockAdminAnalytics: AdminAnalytics = {
  totalUsers: 286,
  activeUsers: 198,
  totalDecisions: 1243,
  completedDecisions: 1045,
  avgDecisionScore: 87.2,
  totalAlternatives: 3847,
  userGrowth: [
    { date: 'May 1', count: 150 },
    { date: 'May 3', count: 165 },
    { date: 'May 5', count: 178 },
    { date: 'May 7', count: 192 },
    { date: 'May 9', count: 205 },
    { date: 'May 11', count: 220 },
    { date: 'May 13', count: 238 },
    { date: 'May 14', count: 286 },
  ],
  decisionTrend: [
    { date: 'May 1', count: 85 },
    { date: 'May 3', count: 92 },
    { date: 'May 5', count: 110 },
    { date: 'May 7', count: 128 },
    { date: 'May 9', count: 145 },
    { date: 'May 11', count: 168 },
    { date: 'May 13', count: 189 },
    { date: 'May 14', count: 198 },
  ],
  decisionsByStatus: [
    { name: 'Completed', value: 1045 },
    { name: 'Pending', value: 178 },
    { name: 'Archived', value: 20 },
  ],
  topCriteria: [
    { name: 'Cost', usage: 892 },
    { name: 'Performance', usage: 756 },
    { name: 'Reliability', usage: 643 },
    { name: 'Ease of Use', usage: 589 },
    { name: 'Scalability', usage: 521 },
  ],
  deviceStats: [
    { device: 'Desktop', users: 145 },
    { device: 'Mobile', users: 89 },
    { device: 'Tablet', users: 34 },
  ],
  dayOfWeekStats: [
    { day: 'Mon', decisions: 185 },
    { day: 'Tue', decisions: 201 },
    { day: 'Wed', decisions: 178 },
    { day: 'Thu', decisions: 219 },
    { day: 'Fri', decisions: 245 },
    { day: 'Sat', decisions: 98 },
    { day: 'Sun', decisions: 117 },
  ],
};

export const mockAdminSettings: AdminSettings = {
  siteName: 'DeciSmart',
  maxDecisionAlternatives: 10,
  maxDecisionCriteria: 15,
  enableAIFeatures: true,
  enableUserRegistration: true,
  maintenanceMode: false,
  emailNotifications: true,
  dataRetentionDays: 365,
};
